### ISSUE TITLE
Deploy and release v2.2.1

### ISSUE THREAD

**Issue by shazow** [vipnode/vipnode#62]
Should include fix @mining-visualizer's bug in https://github.com/vipnode/vipnode/issues/58#issuecomment-510695586

Will close this issue when it's done

**Comment by shazow** [comment]
Decided to just call it v2.2

I deployed it to the demo pool.

Trying to cut a binary release, but having trouble cross-compiling to Windows using xgo, bunch of `/usr/share/mingw-w64/include/oledlg.h` errors. Hmmm.

**Comment by mining-visualizer** [comment]
Hey there,  I just tried v2.2.  Still having some difficulties.  Here's the output from vipnode:

```
2019-07-12 14:56:40.880 INFO Connecting to Ethereum node: /home/russel/.ethereum/geth.ipc
2019-07-12 14:56:40.883 INFO Connecting to remote pool: wss://pool.vipnode.org/
[agent] 2019/07/12 14:56:41 Connected to local geth-light node: enode://30bd5a214285637e900065f4308c7372d3cdf6acca8e2ae981be9b7b45885615b1724bf968c24f1addab569a8b16d6336b02a9235f20f053063d21922ab0cd0f@75.156.28.206:30303?discport=0
[agent] 2019/07/12 14:56:41 Registered on pool: Version vipnode/pool/v2.2
2019-07-12 14:56:41.563 ALERT Message from pool: Welcome to the demo vipnode pool! You can manage your account balance here: https://vipnode.org/pool/?enode=30bd5a214285637e900065f4308c7372d3cdf6acca8e2ae981be9b7b45885615b1724bf968c24f1addab569a8b16d6336b02a9235f20f053063d21922ab0cd0f
[agent] 2019/07/12 14:56:41 Pool update: peers=0 active=0 invalid=0 block=0 balance=Balance(<null account>, 0 wei)
[agent] 2019/07/12 14:56:41 Requesting more kind="geth" peers from pool: 3
agent failed: agent error: Failed during pool peer request: failed to call "vipnode_whitelist" on 1 hosts: invalid enode: missing 'enr:' prefix for base64-encoded record
 -> Error type agent.AgentPoolError is missing an explanation. Please open an issue at https://github.com/vipnode/vipnode
```

And here is what showed up on the geth output around the time I launched vipnode:

```
DEBUG[07-12|15:01:16.866] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[07-12|15:01:36.866] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
DEBUG[07-12|15:01:56.872] Recalculated downloader QoS values       rtt=20s confidence=1.000 ttl=1m0s
TRACE[07-12|15:01:57.842] Accepted RPC connection                  conn=@
DEBUG[07-12|15:01:57.842] Served web3_clientVersion                reqid=1 t=36.8µs
DEBUG[07-12|15:01:57.843] Served eth_protocolVersion               reqid=2 t=26.1µs
DEBUG[07-12|15:01:57.843] Served net_version                       reqid=3 t=19.5µs
WARN [07-12|15:01:57.843] Served admin_addTrustedPeer              reqid=4 t=43.8µs err="invalid enode: missing 'enr:' prefix for base64-encoded record"
INFO [07-12|15:01:57.844] New local node record                    seq=14 id=817f582d11f36973 ip=75.156.28.206 udp=0 tcp=30303
DEBUG[07-12|15:01:57.844] Served admin_nodeInfo                    reqid=5 t=816.3µs
DEBUG[07-12|15:01:58.449] Served admin_nodeInfo                    reqid=6 t=494.9µs
DEBUG[07-12|15:01:58.547] Served admin_peers                       reqid=7 t=265.4µs
```

**Comment by shazow** [comment]
@mining-visualizer Hm, is that geth 1.9? I think some APIs changed, I'll need to try it myself on Monday. Will hold off announcing v2.2 until we figure this out, maybe get v2.2.1 out once we fix it. :)

**Comment by mining-visualizer** [comment]
Yup, v1.9.  I just tried it again with geth 1.8.27 and got the exact same error.

**Comment by shazow** [comment]
Found the problem, will try to get a fix out today! https://github.com/vipnode/vipnode/issues/65

**Comment by shazow** [comment]
FYI #67 is pushed (reviews welcome), going to test it and hopefully deploy soon.

**Comment by shazow** [comment]
I deployed the next release candidate to the demo pool, will keep an eye on it for a bit then do a release once the PR gets merged.

**Comment by shazow** [comment]
Actually published v2.2.1 now: https://github.com/vipnode/vipnode/releases

@mining-visualizer Could you let me know if you're still having problems?

(Sorry about the lack of a Windows build still, xgo is giving me problems)

**Comment by mining-visualizer** [comment]
Don't worry about the Windows build ... I'm running Ubuntu 18.04 on WSL.

I just tried the latest version.  I noticed that `--version` shows v2.2-8-gf8c4d50.  Is that the latest version with the fixes?

Anyways, I ran it and it still gives me the error about the "missing enr: prefix", although now it keep running and tries again every so often.  

I did notice something in the geth console ... a few seconds after starting vipnode, a line came up in geth saying 'New local node record', with a bunch of numbers after and my public IP address.  Does that tell you anything.

Here is the output from vipnode:
```
2019-07-15 19:03:05.903 INFO Connecting to Ethereum node: /home/pi/.ethereum/geth.ipc
2019-07-15 19:03:05.922 INFO Connecting to remote pool: wss://pool.vipnode.org/
[agent] 2019/07/15 19:03:06 Connected to local geth-light node: enode://897aa04adb9b6178843b6a7ad30d6ba4ff0c93d1d9fdda6d8cf115a2e19a4f9d667e0841c28270c4461e0a145a2453627a7516008ee7c55cfe66e0e5e4c5bfaf@75.156.28.206:30303
[agent] 2019/07/15 19:03:06 Registered on pool: Version vipnode/pool/v2.2-7-gbe0ea59
2019-07-15 19:03:06.914 ALERT Message from pool: Welcome to the demo vipnode pool! You can manage your account balance here: https://vipnode.org/pool/?enode=897aa04adb9b6178843b6a7ad30d6ba4ff0c93d1d9fdda6d8cf115a2e19a4f9d667e0841c28270c4461e0a145a2453627a7516008ee7c55cfe66e0e5e4c5bfaf
[agent] 2019/07/15 19:03:07 Pool update: peers=8 active=0 invalid=0 block=8159194 balance=Balance(<null account>, 0 wei)
[agent] 2019/07/15 19:03:07 Requesting more kind="geth" peers from pool: 3
[agent] 2019/07/15 19:03:07 AddPeers RPC failed (possibly due to outdated agents on the pool): failed to call "vipnode_whitelist" on 1 hosts: invalid enode: missing 'enr:' prefix for base64-encoded record
[agent] 2019/07/15 19:04:07 Pool update: peers=8 active=0 invalid=0 block=8159195 balance=Balance(<null account>, 0 wei)
[agent] 2019/07/15 19:04:07 Requesting more kind="geth" peers from pool: 3
[agent] 2019/07/15 19:04:08 AddPeers RPC failed (possibly due to outdated agents on the pool): failed to call "vipnode_whitelist" on 1 hosts: invalid enode: missing 'enr:' prefix for base64-encoded record
```

**Comment by mining-visualizer** [comment]
Oh, hey!  Maybe it is working.  Geth just said "Block synchronisation started", and it is importing headers.  Not sure why vipnode is spitting out all those error messages.  I'll leave geth running for awhile and see what happens.

**Comment by shazow** [comment]
@mining-visualizer Looks like it's working!

Let me know if these messages are too scary/confusing:
> [agent] 2019/07/15 19:04:08 AddPeers RPC failed (possibly due to outdated agents on the pool): failed to call "vipnode_whitelist" on 1 hosts: invalid enode: missing 'enr:' prefix for base64-encoded record

This happens when the pool tries to match you up with another agent but fails because that other agent responded with an error. That is, it's not your fault, but the other node's fault. I was hoping to temper it with " (possibly due to outdated agents on the pool)" but I'd love suggestions on phrasing. :)

I'll fix up the binaries to have the correct version. Yours should be equivalent to the tagged version but my environment was incorrect. I need to revise my build process. -_-

**Comment by shazow** [comment]
This was done a few months ago, oops.
